# Custom Language File for Launcher Customizer

[ejs.app]
title = "Sample"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/sample"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/sample"
supportLink = "https://github.com/mchlauncher/sample/issues"

[ejs.welcome]
welcomeHeader = "Sample"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."